Vagrant.configure("2") do |config|
    config.vm.box = "debian/jessie64"
    config.vm.hostname = "server.sectesting.com"
    config.vm.network "private_network", ip: "192.168.0.13",
    virtualbox__intnet: "sectesting"
    config.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
    end
config.vm.provision "shell", path: "script.sh"
end